---
stages:
  - deploy
  - module-pipelines


kubernetes:
  stage: module-pipelines
  trigger:
    include:
      - "kubernetes/.gitlab-ci.yml"
    strategy: depend # depend нужен, если какой-нибудь дочерний пайплайн свалился, мы знали, что общий пайплайн тоже идёт с ошибкой
  only:
    changes: # как только происходит изменение в папке kubernetes, запускается дочерний пайплайн, который лежит в этой папке
      - kubernetes/**/*
