---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-backend-report
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
    env: "{{ .Values.environment }}" 
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }} 
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: backend-report-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: backend-report-{{ .Release.Name }}
    spec:
      containers:
        - name: backend-report-{{ .Release.Name }}
          image: {{ .Values.container.image }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          imagePullPolicy: IfNotPresent
          env:
            - name: DB
              value: {{ .Values.database.url }}
            - name: VAULT_HOST
              value: {{ .Values.vault.host }}
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_token
          ports:
            - name: backend-report
              containerPort: 8084
      imagePullSecrets:
        - name: docker-config-secret

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-report-{{ .Release.Name }}-hpa
  labels:
    app: backend-report-{{ .Release.Name }}-hpa
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-report-{{ .Release.Name }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75 