---
apiVersion: v1
kind: Service
metadata:
  name: backend-{{ .Release.Name }}
  labels:
    app: backend-{{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend-{{ .Release.Name }} 